name: Feature Request
description: Request a new feature for Octogram
labels: ["feature"]
title: "[Feature]: <title-here>"
body:
  - type: markdown
    attributes:
      value: |
        # Octogram Feature Request
        Thank you for helping us improve Octogram! Please follow these guidelines when requesting a new feature:

        - **Check for Duplicates:** Ensure you have checked existing requests to avoid duplication. Duplicate requests will be closed.
        - **Be detailed:** Provide as much detail as possible to help us understand your request.
        - **Do not ask to explicitly take unique features from other clients:** Please do not ask.
        - **English Only:** Please use English when submitting your request. Requests in other languages will be closed.

        ---

  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: By submitting this request, you agree to the following
      options:
        - label: Checked for similar requests and confirmed this is unique
          required: true

  - type: markdown
    attributes:
      value: |
        ---

  - type: textarea
    attributes:
      label: Feature Description
      description: Describe the feature you would like to see added to Octogram. Please be as detailed as possible.
      placeholder: Add a description of the feature here.
    validations:
      required: true